env:
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
rules:
  "comma-dangle": ["error", "never"]
<<<<<<< HEAD
  "linebreak-style": ["error", "windows"]
=======
>>>>>>> 86dc72ba15aebfd548e9b1f30e78e3e04258a515
